#!/usr/bin/env python

# Author: Pablo Abelenda
# Contact: pablo.abelenda@interoud.com

import sys

reload(sys)
sys.setdefaultencoding('utf-8')
print sys.getdefaultencoding()


from django.core.management import setup_environ
import imp

try:
    imp.find_module('settings') # Assumed to be in the same directory.
except ImportError:
    import sys
    sys.stderr.write('''Error: Can't find the file 'settings.py' in the
    directory containing %r. It appears you've customized things.\n
    You'll have to run django-admin.py, passing it your settings
    module.\n''' % __file__)
    sys.exit(1)


import settings

# execute_manager(settings)
setup_environ(settings)

from asm.models import *



from optparse import OptionParser
from datetime import datetime
import time, pytz

parser = OptionParser()
parser.add_option("-k", "--keepbackdays", dest="days",
                  help="Days to keep back", metavar="DAYS",
                  default=7)

(options, args) = parser.parse_args()


now_seconds = int(time.time())
seconds_of_week = int(options.days) * 24 * 60 * 60
iter_startkey=now_seconds-seconds_of_week
objs = ASM_Job.objects.filter(creation_date__lt=datetime.fromtimestamp(iter_startkey,pytz.UTC))

for o in objs:
    print "Deleting " + unicode(o) + " (" + str(o.creation_date) + ")"
    o.delete()

